---
title: "NAME OF CLIENT AND PROJECT Summary Tables"
author: "CHILOMBO CONSULTING"
date: "MM/DD/YEAR"
output: word_document
---

**_CLearing the environment_**
```{r include=FALSE}

rm(list = ls())
```


**_Setting working directory)**
```{r}
setwd("~/Documents/R/Chilombo Consulting/NAME OF CLIENT")
```

**Installing packages Loading libraries_**
```{r}

#packages already installed, if running for the first time add below
remotes::install_github("ddsjoberg/gtsummary")
install.packages("writexl")
#run libraries
require(readxl)
library(devtools)
library(dplyr)
library(tidyverse)
library(tidyr)
library(stringr)
library(padr)
library(gtsummary)
library(dtplyr)
library(writexl)




```

**_Determining the size of the dataset before opening it_**
```{r}
file.info('Data.xlsx')$size
#about 1 MB; not a big data venture by any means
```

**_Reading data_**
```{r}

Data_raw = read_xlsx("~/Documents/R/Chilombo Consulting/NAME OF CLIENT/Data.xlsx")
```



**_Variable cleaning for each question that needs re categorization**
```{r}
Data_master_2<-Data_master %>% 
#create Q17 Race/Ethnicity groupings (URM/non-URM/White/Prfer not to Say) from Q17 
  mutate(`Q17_Race_Ethnicity` =  ifelse(Q17 =="White"  , "White",
                                 ifelse(Q17 == "Mixed Race/Biracial"  | Q17== "Black or African American" | 
                                        Q17== "Hispanic and/or Latino/a/e/x"|
                                        Q17=="Hispanic and/or Latino/a/e/x,White" |
                                        Q17=='Black or African American,East Asian/East Asian American',"URM",
                                ifelse(Q17 == "Prefer Not to Say",
                                      "Prefer Not to Say",
                                  ifelse( Q17 == "East Asian/East Asian American"  | Q17== "Middle Eastern/Northern African/West Asian" |
                                         Q17== "Middle Eastern/Northern African/West Asian,White"|
                                           Q17=="East Asian/East Asian   American,Other" | Q17=="South Asian/South Asian American"
                                         | Q17=="South Asian/South Asian American,White" |Q17== "East Asian/East Asian American,Other" |
                                           Q17=="East Asian/East Asian American,South Asian/South Asian American" | Q17=="Middle Eastern/Northern African/West Asian,White,Mixed Race/Biracial"
                                         , "Non-URM", NA
))))) %>% 

            

```

**_Master Univariate Table_**
```{r}
 Univariate<-Data_master_clean 

 Univariate%>%
  tbl_summary(digits = ~ 0,
   missing_text = "(Missing)",
     sort = list(everything() ~ "frequency")) %>% 
  modify_header(label ~ "**Univariate Table**") %>%  
  modify_caption("**Univariate Table*") %>%
  modify_footnote(everything() ~ NA) %>% #removes superscript from header
  #modify_footnote(all_stat_cols() ~ "missing values for Participant Type dropped; n (%)") %>% 
  bold_labels() %>% 
    as_gt() 
```

**_Master Participant_Type Table_**
```{r}
 Participant_Type<-Data_master_clean %>% 
    dplyr::select( -c('Q18_FGCS':'Q18_IS')) #remove all other identity groups from analysis

Participant_Type%>%
tbl_summary(by = `Q1_Participant Type`, digits = ~ 0,
   missing_text = "(Missing)", sort = list(everything() ~ "frequency")) %>% 
  modify_header(label ~ "**Participant Type**") %>%  
  modify_caption("**Table 1. Participant Type**") %>%
  modify_footnote(everything() ~ NA) %>% #removes superscript from header
  #modify_footnote(all_stat_cols() ~ "missing values for Participant Type dropped; n (%)") %>% 
  bold_labels() %>% 
    as_gt() 
```
**_Master Gender Table_**
```{r}
 Gender_Identity<-Data_master_clean %>% 
    dplyr::select( -c('Q18_FGCS':'Q18_IS')) #remove all other identity groups from analysis

 Gender_Identity%>%
  tbl_summary(by = `Q16_Gender Identity`, digits = ~ 0,
   missing_text = "(Missing)", sort = list(everything() ~ "frequency")) %>% 
  modify_header(label ~ "**Gender Identity**") %>%  
  modify_caption("**Table 2. Gender Identity**") %>%
     modify_footnote(everything() ~ NA) %>% #removes superscript from header
 # modify_footnote(all_stat_cols() ~ "missing values for Gender Identity dropped; n (%)") %>% 
  bold_labels() %>% 
    as_gt() 
```


**_Final Clean Dataset_**
```{r}
write.table(Data_master_clean, paste ('Clean Dataset/NAME OF CLIENT_', Sys.Date(), ".txt"), sep ="\t", row.names=FALSE)

```

